plugins: ['prettier-plugin-packagejson', 'prettier-plugin-sort-json']
printWidth: 120
semi: false
singleQuote: true
trailingComma: 'none'
overrides:
  - files: ['*.json']
    options:
      jsonRecursiveSort: true
  - files: ['*.yaml']
    options:
      printWidth: 300
