# Updated: 2024-06-21 10:10:08
# Author: Theo-Messi
# Homepage: https://github.com/Theo-messi

##############   注意:该配置文件为meta内核专用,不适合其他clash内核   #################

###############################   建立锚点   #####################################
pp: &pp {type: http, interval: 86400, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 600, format: yaml}}    #####   订阅锚点   #####
pc: &pc {type: http, behavior: classical, interval: 86400, format: yaml}    #####   rule-providers锚点   #####
pd: &pd {type: http, behavior: domain, interval: 86400, format: yaml}    #####   rule-providers锚点   #####
pi: &pi {type: http, behavior: ipcidr, interval: 86400, format: yaml}    #####   rule-providers锚点   #####
o1: &o1 {type: select, proxies: [🚀 节点选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇨🇳 台湾节点, 🇸🇬 狮城节点, 🇯🇵 日本节点, 🇺🇸 美国节点, 💠 其他地区, 🎯 全球直连], include-all-providers: true}    ######  策略组描点   ######
o2: &o2 {type: select, proxies: [🎯 全球直连, 🚀 节点选择, ♻️ 自动选择, 🇭🇰 香港节点, 🇨🇳 台湾节点, 🇸🇬 狮城节点, 🇯🇵 日本节点, 🇺🇸 美国节点, 💠 其他地区]}
###############################   建立锚点   #####################################

########################################################################分隔符
# url 里填写自己的订阅 sub1 or sub2 修改成订阅名称
proxy-providers:
  sub1:     ###订阅名称###
    <<: *pp
    url: ""

  sub2:    ##订阅名称###
    <<: *pp
    url: ""

  sub3:    ##订阅名称###
    <<: *pp
    url: ""

########################################################################分隔符
proxy-groups:
  - {name: 🚀 节点选择, type: select, proxies: [♻️ 自动选择, 🇭🇰 香港节点, 🇨🇳 台湾节点, 🇸🇬 狮城节点, 🇯🇵 日本节点, 🇺🇸 美国节点, 💠 其他地区], include-all-providers: true}
  - {name: ♻️ 自动选择, type: url-test, interval: 600, tolerance: 100, lazy: true, url: https://www.gstatic.com/generate_204, include-all-providers: true}
  - {name: 📲 电报信息, <<: *o1}
  - {name: 📱 Twitter, <<: *o1}
  - {name: 💬 OpenAi, <<: *o1}
  - {name: 🎬 油管视频, <<: *o1}
  - {name: 🎥 奈飞视频, <<: *o1}
  - {name: 🏰 Disney, <<: *o1}
  - {name: 📽️ 巴哈姆特, type: select, proxies: [🇨🇳 台湾节点, 🇭🇰 香港节点, 🚀 节点选择]}
  - {name: 📺 哔哩哔哩, type: select, proxies: [🎯 全球直连, 🇨🇳 台湾节点, 🇭🇰 香港节点]}
  - {name: 🌎 国外媒体, <<: *o1}
  - {name: 🌏 国内媒体, type: select, proxies: [🎯 全球直连, 🇨🇳 台湾节点, 🇭🇰 香港节点, 🚀 节点选择]}
  - {name: ☣️ Copilot, <<: *o1}
  - {name: Ⓜ️ 微软服务, <<: *o2}
  - {name: 🍎 苹果服务, <<: *o2}
  - {name: 🎮 游戏平台, <<: *o2}
  - {name: 🔰 下载平台, <<: *o2}
  - {name: 🎯 全球直连, type: select, proxies: [DIRECT,REJECT]}
  #- {name: 🍃 广告拦截, type: select, proxies: [REJECT,DIRECT]}
  - {name: 🐟 漏网之鱼, <<: *o1}
#地区策略组
  - {name: 🇭🇰 香港节点, type: select, include-all-providers: true, filter: "(?i)港|hk|hongkong|hong kong"}
  - {name: 🇨🇳 台湾节点, type: select, include-all-providers: true, filter: "(?i)台|tw|taiwan|tai wan"}
  - {name: 🇸🇬 狮城节点, type: select, include-all-providers: true, filter: "(?i)新加坡|sg|singapore|狮城"}
  - {name: 🇯🇵 日本节点, type: select, include-all-providers: true, filter: "(?i)日|jp|japan"}
  - {name: 🇺🇸 美国节点, type: select, include-all-providers: true, filter: "(?i)美|us|unitedstates|united states"}
  - {name: 💠 其他地区, type: select, include-all-providers: true, filter: "(?i)^(?!.*(?:🇭🇰|🇯🇵|🇺🇸|🇸🇬|🇨🇳|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore|美|us|unitedstates)).*"}

rules:
  - RULE-SET,TheoDirect,🎯 全球直连
  - RULE-SET,TheoDiversion,🚀 节点选择
  - DOMAIN,search.iscrv.com,🎯 全球直连
  - DOMAIN-SUFFIX,googleapis.cn,🚀 节点选择
  - DOMAIN-SUFFIX,xn--ngstr-lra8j.com,🚀 节点选择
  - RULE-SET,LocalAreaNetwork,🎯 全球直连
  - RULE-SET,Unban,🎯 全球直连
  # - RULE-SET,BanEasyListChina,🍃 广告拦截
  # - RULE-SET,BanAD,🍃 广告拦截
  # - RULE-SET,BanEasyList,🍃 广告拦截
  # - RULE-SET,BanEasyPrivacy,🍃 广告拦截
  - RULE-SET,Telegram,📲 电报信息
  - RULE-SET,Twitter,📱 Twitter
  - RULE-SET,OpenAi,💬 OpenAi
  - RULE-SET,YouTube,🎬 油管视频
  - RULE-SET,Disney,🏰 Disney
  - RULE-SET,Netflix,🎥 奈飞视频
  - RULE-SET,Bahamut,📽️ 巴哈姆特
  - RULE-SET,ProxyMedia,🌎 国外媒体
  - RULE-SET,Category-games,🎮 游戏平台
  - RULE-SET,Bilibili,📺 哔哩哔哩
  - RULE-SET,Download,🔰 下载平台
  - RULE-SET,ChinaMedia,🌏 国内媒体
  - RULE-SET,Copilot,☣️ Copilot
  - DOMAIN,sydney.bing.com,☣️ Copilot
  - RULE-SET,Microsoft,Ⓜ️ 微软服务
  - RULE-SET,Apple,🍎 苹果服务
  - RULE-SET,Geosite_cn,🎯 全球直连
  - RULE-SET,Geosite_private,🎯 全球直连
  - RULE-SET,ChinaDomain,🎯 全球直连
  - RULE-SET,Geolocation-!cn,🚀 节点选择,no-resolve
  - RULE-SET,Geoip_cn,🎯 全球直连,no-resolve
  - RULE-SET,Geoip_private,🎯 全球直连,no-resolve
  - RULE-SET,ChinaCompanyIp,🎯 全球直连,no-resolve
  - RULE-SET,ChinaIp,🎯 全球直连,no-resolve
  - DST-PORT,22,🇭🇰 香港节点
  - MATCH,🐟 漏网之鱼

rule-providers:
  TheoDirect:
    <<: *pc
    url: "https://raw.githubusercontent.com/Theo-messi/dotfiles/main/clash/TheoDirect.yaml"
  TheoDiversion:
    <<: *pc
    url: "https://raw.githubusercontent.com/Theo-messi/dotfiles/main/clash/TheoDiversion.yaml"
  Geolocation-!cn:
    <<: *pd
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.yaml"  
  LocalAreaNetwork:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml"
  Unban:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/UnBan.yaml" 
  # BanEasyListChina:
  #   <<: *pc
  #   url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyListChina.yaml"
  # BanAD:
  #   <<: *pc
  #   url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml"
  # BanEasyList:
  #   <<: *pc
  #   url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyList.yaml"
  # BanEasyPrivacy:
  #   <<: *pc
  #   url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyPrivacy.yaml"
  Telegram:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Telegram.yaml"
  Twitter:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Twitter.yaml"
  OpenAi:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/OpenAi.yaml"
  YouTube:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/YouTube.yaml"
  Netflix:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Netflix.yaml"
  Disney:
    <<: *pc
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.yaml" 
  Bahamut:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Bahamut.yaml"
  ProxyMedia:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyMedia.yaml"
  Category-games:
    <<: *pd
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games.yaml"
  Bilibili:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Bilibili.yaml" 
  Download:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Download.yaml"
  ChinaMedia:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaMedia.yaml"   
  GoogleFCM:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleFCM.yaml"  
  Microsoft:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Microsoft.yaml"
  Copilot:
    <<: *pc
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot_No_Resolve.yaml"
  Apple:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Apple.yaml"
  Geosite_cn:
    <<: *pd
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.yaml"
  Geosite_private:
    <<: *pd
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.yaml"
  ChinaDomain:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaDomain.yaml"
  Geoip_cn:
    <<: *pi
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.yaml"
  Geoip_private:
    <<: *pi
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.yaml"
  ChinaCompanyIp:
    <<: *pi
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaCompanyIp.yaml"
  ChinaIp:
    <<: *pi
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaIp.yaml"

mixed-port: 7890
allow-lan: true
ipv6: true     ###开启ipv6
mode: Rule
log-level: debug
external-controller: 0.0.0.0:9090
secret: "123456"
find-process-mode: strict
global-client-fingerprint: chrome
global-ua: clash-verge/v1.5.10
profile:
  store-selected: true
  store-fake-ip: true

dns:
  enable: true
  ipv6: true     ###关闭IPV6 dns解析
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  nameserver: 
    - 119.29.29.29
    - 223.5.5.5
  default-nameserver:
    - 223.5.5.5
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://dns.pub/dns-query
  #nameserver-policy: 
  #  'rule-set:Bahamut':
  #    - 'https://dns.google/dns-query#📽️ 巴哈姆特'
  #    - 'https://dns.cloudflare.com/dns-query#📽️ 巴哈姆特'
  #  'rule-set:Geolocation-!cn':
  #    - 'https://dns.google/dns-query#🚀 节点选择'
  #    - 'https://dns.cloudflare.com/dns-query#🚀 节点选择'

  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time-ios.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - "+.pool.ntp.org"
    - time1.cloud.tencent.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - "+.qq.com"
    - "+.tencent.com"
    - "+.srv.nintendo.net"
    - "*.n.n.srv.nintendo.net"
    - "+.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - "+.battlenet.com.cn"
    - "+.wotgame.cn"
    - "+.wggames.cn"
    - "+.wowsgame.cn"
    - "+.wargaming.net"
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
    - heartbeat.belkin.com
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - na.b.g-tun.com
    - "+.nflxvideo.net"
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.ff14.sdo.com"
    - ff.dorado.sdo.com
    - "*.mcdn.bilivideo.cn"
    - "+.media.dssott.com"
    - shark007.net
    - Mijia Cloud
    - "+.cmbchina.com"
    - "+.cmbimg.com"
    - local.adguard.org
    - "+.sandai.net"
    - "+.n0808.com"
    - controlplane.tailscale.com
    - log.tailscale.io
