name: Test sh

on:
  push:
    paths:
      - '_install/setup_linux.sh'
      - '_install/setup_zsh.sh'
  workflow_dispatch:

jobs:
  setup_environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run setup_linux.sh
        run: curl -o- https://raw.githubusercontent.com/Theo-Messi/dotfiles/main/_install/setup_linux.sh | bash

      - name: Run setup_zsh.sh
        run: curl -o- https://raw.githubusercontent.com/Theo-Messi/dotfiles/main/_install/setup_zsh.sh | bash
        
  ## Brak通知流程运行状态
      - name: Get current date
        id: current_date
        run: echo "DATE=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        
      - name: Translate job status to Chinese
        id: translate-status
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "translated_status=成功" >> $GITHUB_ENV
          elif [ "${{ job.status }}" == "failure" ]; then
            echo "translated_status=失败" >> $GITHUB_ENV
          elif [ "${{ job.status }}" == "cancelled" ]; then
            echo "translated_status=取消" >> $GITHUB_ENV
          else
            echo "translated_status=未知" >> $GITHUB_ENV
          fi

      - name: Notify job status
        if: always()  # 确保这一步始终运行，不管之前的步骤是否成功
        run: |
          curl -X "POST" "${{ secrets.BARK_KEY }}" \
             -H 'Content-Type: application/json; charset=utf-8' \
             -d '{
                    "body": "${{ github.repository }}/_install/*.sh于${{ env.DATE }}运行${{ env.translated_status }}",
                    "title": "Github Actions",
                    "badge": 1,
                    "category": "Github Actions",
                    "sound": "multiwayinvitation.caf",
                    "icon": "https://cdn.pixabay.com/photo/2022/01/30/13/33/github-6980894_1280.png",
                    "group": "Github Actions"
                  }'
